<?xml version="1.0"?>
<robot name="onrobot_hex_v2" xmlns:xacro="http://wiki.ros.org/xacro">
<!-- 
  Xacro Macro for the OnRobot Hexa V2 Force Torque Sensor
  author: Achu Wilson
          achuw@andrew.cmu.edu
  Date: Oct 15 2021
-->
<!-- Define the height and radius of the Onrobot Hexa V2 force torque sensor-->
<xacro:property name="ft_height" value="0.0375" />
<xacro:property name="ft_radius" value="0.035" />

<!-- Define the Onrobot F/T sensor as a macro-->
 <xacro:macro name="onrobot_ft" params="prefix ">
 <link name="${prefix}base_link">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 ${ft_height/2.0}" />
      <geometry>
        <cylinder radius="${ft_radius}" length="${ft_height}" />
      </geometry>
      <material name="blue">
        <color rgba="0 0 .8 1"/>
      </material>
    </visual>

    <collision>
     <origin rpy="0 0 0" xyz="0 0 ${ft_height/2.0}" />
      <geometry>
         <cylinder radius="${ft_radius}" length="${ft_height}" />
      </geometry>
    </collision>
</link>

<!--Add a flange to attach the gripper/end effector to the FT sensor-->
<link name="${prefix}flange"/>
<joint name="${prefix}base-flange" type = "fixed">
  <origin xyz="0 0 ${ft_height} " rpy=" 0 0 0 "/>
  <parent link="${prefix}base_link" />
  <child link = "${prefix}flange" />
</joint>

</xacro:macro>

<!--Uncomment and instantiate the macro, if you need to view standalone-->
<!--xacro:onrobot_ft prefix = ""/ -->  
</robot>