<?xml version="1.0"?>
<robot name="wsg50" xmlns:xacro="http://wiki.ros.org/xacro">
<!--
  Xacro Macro for the WSG50 Gripper
  author: Achu Wilson
          achuw@andrew.cmu.edu
  Date: Oct 16 2021
-->
<!-- Define the height, length, width-->
<xacro:property name="wsg_height" value="0.185" />
<xacro:property name="wsg_length" value="0.21" />
<xacro:property name="wsg_width" value="0.06" />
<!--finger_center is the distance between the base of wsg50 and centre contact position of the finger-->
<xacro:property name="finger_center" value="0.15" />



<!-- Define wsg50 gripper as a macro-->
 <xacro:macro name="wsg50" params="prefix">
 <link name="${prefix}base_link">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 ${wsg_height/2.0}" />
      <geometry>
        <box size="${wsg_length} ${wsg_width} ${wsg_height} " />
      </geometry>
      <material name="green">
        <color rgba="0 0.8 0 1"/>
      </material>
    </visual>

    <collision>
     <origin rpy="0 0 0" xyz="0 0 ${wsg_height/2.0}" />
      <geometry>
         <box size="${wsg_length} ${wsg_width} ${wsg_height} " />
      </geometry>
    </collision>
</link>

<!--Add a frame/link to the middle of the gripper, so that we can use that for kinematics-->
<link name="${prefix}finger"/>
<joint name="${prefix}base-finger" type = "fixed">
  <origin xyz="0 0 ${finger_center} " rpy=" 0 0 0 "/>
  <parent link="${prefix}base_link" />
  <child link = "${prefix}finger" />
</joint>

</xacro:macro>


<!--Uncomment and instantiate the macro, if you need to view standalone-->
<!--xacro:wsg50 prefix = ""/ -->
</robot>